version: "3"
services:
  db:
    image: mysql
    container_name: mysql.test
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: adminer.test
    restart: always
    ports:
      - 8080:8080



